name: Pull Request

on:
    pull_request:
        branches:
            - main
        paths:
            - force-app/**

jobs:
    code-analyze:
        name: Run Salesforce Code Analyzer
        uses: ./.github/workflows/code-analyze.yml
        secrets: inherit
    create-package-beta:
        name: Run Create Package Beta Workflow
        uses: ./.github/workflows/create-package-beta.yml
        secrets: inherit
